/**
 *
 * @author nestor
 */

import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class EscenaMenu extends JFrame {

    /**
     * Variables
     */

    
    /**
     * Creates new form EscenaMenu
     */
    public EscenaMenu() {
        initComponents();
        juego = new EscenaJuego();
        juego.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCanvas = new javax.swing.JPanel();
        buttonInicio = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        panelCanvas.setBackground(new java.awt.Color(255, 150, 0));
        panelCanvas.setLayout(new java.awt.GridBagLayout());

        buttonInicio.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        buttonInicio.setText("Start");
        buttonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInicioMouseClicked(evt);
            }
        });
        buttonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        panelCanvas.add(buttonInicio, gridBagConstraints);

        labelTitulo.setFont(new java.awt.Font("Lobster", 1, 36)); // NOI18N
        labelTitulo.setForeground(java.awt.Color.white);
        labelTitulo.setText("The best game");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        panelCanvas.add(labelTitulo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInicioActionPerformed

    private void buttonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInicioMouseClicked
        this.setVisible(false);
        juego.setVisible(true);
    }//GEN-LAST:event_buttonInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscenaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonInicio;
    public javax.swing.JLabel labelTitulo;
    public javax.swing.JPanel panelCanvas;
    // End of variables declaration//GEN-END:variables
    public EscenaJuego juego;

}
