/**
 *
 * @author nestor
 */
public class EscenaFinal extends javax.swing.JFrame {

    /**
     * Creates new form EscenaFinal
     */
    public EscenaFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        canvas = new javax.swing.JPanel();
        finalScore = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The end");
        setBackground(new java.awt.Color(255, 150, 0));

        canvas.setBackground(new java.awt.Color(255, 150, 0));
        canvas.setLayout(new java.awt.GridBagLayout());

        finalScore.setFont(new java.awt.Font("Lobster", 1, 46)); // NOI18N
        finalScore.setForeground(java.awt.Color.white);
        finalScore.setText("Final Score");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        canvas.add(finalScore, gridBagConstraints);

        score.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        score.setForeground(java.awt.Color.white);
        score.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 40;
        canvas.add(score, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        



    // Variables declaration - do not modify                     
    public javax.swing.JPanel canvas;
    public javax.swing.JLabel finalScore;
    public javax.swing.JLabel score;
    // End of variables declaration                   
}
